# Key notes:
- The number of hidden units a parameter of the network, often called a hyperparameter to differentiate it from the weights and biases parameters.  
- Numpy type can be converted to Tensor and vice versa
`torch.from_numpy()` and `[tensor_variable].numpy()`  
- The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [1]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.19888113, 0.72557158, 0.90036198],
       [0.42424883, 0.27672152, 0.91733116],
       [0.28047396, 0.9059148 , 0.81474844],
       [0.47564918, 0.73300723, 0.09884922]])

In [2]:
import torch
b = torch.from_numpy(a)
b

tensor([[0.1989, 0.7256, 0.9004],
        [0.4242, 0.2767, 0.9173],
        [0.2805, 0.9059, 0.8147],
        [0.4756, 0.7330, 0.0988]], dtype=torch.float64)

In [3]:
b.numpy()

array([[0.19888113, 0.72557158, 0.90036198],
       [0.42424883, 0.27672152, 0.91733116],
       [0.28047396, 0.9059148 , 0.81474844],
       [0.47564918, 0.73300723, 0.09884922]])

In [4]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[0.3978, 1.4511, 1.8007],
        [0.8485, 0.5534, 1.8347],
        [0.5609, 1.8118, 1.6295],
        [0.9513, 1.4660, 0.1977]], dtype=torch.float64)

In [5]:
# Numpy array matches new values from Tensor
a

array([[0.39776227, 1.45114316, 1.80072395],
       [0.84849766, 0.55344304, 1.83466231],
       [0.56094792, 1.8118296 , 1.62949688],
       [0.95129836, 1.46601445, 0.19769843]])